import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F5F7FA',
    },
    container: {
        flex: 1,
    },
    listContent: {
        padding: 20,
        paddingBottom: 100, 
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        marginBottom: 16,
        flexDirection: 'row',
        overflow: 'hidden', 
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 4,
    },
    severityStripe: {
        width: 6,
        height: '100%',
    },
    cardContent: {
        flex: 1,
        padding: 16,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#2C3E50',
        marginBottom: 4,
    },
    cardType: {
        fontSize: 14,
        color: '#7F8C8D',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    severityBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: '#F0F2F5',
    },
    severityText: {
        fontSize: 12,
        fontWeight: '700',
    },
    cardNotes: {
        fontSize: 14,
        color: '#555',
        fontStyle: 'italic',
        marginBottom: 12,
        backgroundColor: '#F8F9FA',
        padding: 10,
        borderRadius: 8,
    },
    deleteButton: {
        alignSelf: 'flex-end',
        padding: 8,
    },
    deleteButtonText: {
        color: '#E74C3C',
        fontSize: 13,
        fontWeight: '600',
    },
    badgeGreen: { backgroundColor: '#E8F8F5' },
    badgeOrange: { backgroundColor: '#FEF5E7' },
    badgeRed: { backgroundColor: '#FADBD8' },
    
    emptyContainer: {
        alignItems: 'center',
        marginTop: 60,
    },
    emptyEmoji: {
        fontSize: 60,
        marginBottom: 20,
        opacity: 0.8,
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2C3E50',
        marginBottom: 8,
    },
    emptySub: {
        fontSize: 16,
        color: '#95A5A6',
    },
    fab: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#0d214f',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#0d214f",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    fabText: {
        fontSize: 32,
        color: '#FFFFFF',
        fontWeight: '300',
        marginTop: -4,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        maxHeight: height * 0.9, 
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#2C3E50',
    },
    closeIcon: {
        fontSize: 24,
        color: '#95A5A6',
        padding: 5,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '700',
        color: '#34495E',
        marginBottom: 10,
        marginTop: 15,
    },
    inputSubLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#7F8C8D',
        marginBottom: 8,
        marginLeft: 4,
    },
    input: {
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#E0E6ED',
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        color: '#2C3E50',
    },
    textArea: {
        height: 80,
        textAlignVertical: 'top',
    },
    chipsContainer: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    chip: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 25,
        backgroundColor: '#F0F2F5',
        marginRight: 10,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    chipSelected: {
        backgroundColor: '#EBF5FB',
        borderColor: '#3498DB',
    },
    chipText: {
        color: '#7F8C8D',
        fontWeight: '600',
    },
    chipTextSelected: {
        color: '#2980B9',
        fontWeight: '700',
    },
    suggestionsContainer: {
        flexDirection: 'row',
        marginBottom: 10,
        height: 50, 
    },
    suggestionChip: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#E0E6ED',
        marginRight: 8,
        height: 36,
        justifyContent: 'center',
    },
    suggestionChipSelected: {
        backgroundColor: '#D5F5E3',
        borderColor: '#27AE60',
    },
    suggestionText: {
        color: '#555',
        fontSize: 13,
    },
    suggestionTextSelected: {
        color: '#1E8449',
        fontWeight: 'bold',
    },
    severitySelector: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 5,
    },
    severityOption: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#E0E6ED',
        borderRadius: 12,
        marginHorizontal: 4,
        backgroundColor: '#FFFFFF',
    },
    severityOptionSelected: {
        backgroundColor: '#FFFFFF',
        borderWidth: 2,
    },
    severityDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 8,
    },
    severityOptionText: {
        fontSize: 14,
        color: '#7F8C8D',
    },
    saveButton: {
        backgroundColor: '#0d214f',
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 30,
        marginBottom: 20,
        shadowColor: "#0d214f",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: 'bold',
    },
});

export default styles;