import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F0F2F5',
    },
    header: {
        paddingTop: 20,
        paddingBottom: 20,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 25,
        borderBottomRightRadius: 25,
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    greetingText: {
        fontSize: 22,
        fontWeight: '300',
        color: '#E1E1E6',
    },
    menuButton: {
        padding: 10,
    },
    menuBar: {
        width: 25,
        height: 3,
        backgroundColor: '#FFFFFF',
        borderRadius: 2,
        marginVertical: 2,
    },
    gridContainer: {
        paddingHorizontal: 10,
        paddingTop: 20,
    },
    serviceButtonContainer: {
        flex: 1,
        maxWidth: '50%',
        padding: 8,
    },
    serviceButton: {
        width: '100%',
        aspectRatio: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 8,
        borderWidth: 3,
        borderColor: '#699eeeff',
    },
    serviceButtonPressed: {
        transform: [{ scale: 0.96 }],
        shadowOpacity: 0.05,
        elevation: 2,
    },
    serviceIcon: {
        width: '85%',
        height: '85%',
        resizeMode: 'contain',
        marginBottom: 10,
    },
    serviceLabel: {
        fontSize: 15,
        fontWeight: 'bold',
        color: 'hsla(227, 28%, 29%, 1.00)',
        textAlign: 'center',
    },
    logoutButton: {
        marginHorizontal: 8,
        marginTop: 10,
        marginBottom: 20,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E74C3C',
        paddingVertical: 15,
        borderRadius: 20,
        alignItems: 'center',
    },
    logoutButtonText: {
        color: '#E74C3C',
        fontSize: 16,
        fontWeight: 'bold',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-start',
    },
    drawerContainer: {
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 0,
        width: width * 0.75,
        maxWidth: 320,
        shadowColor: "#000",
        shadowOffset: { width: -2, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 10,
    },
    drawerGradient: {
    flex: 1,
},
    drawerHeader: {
        paddingTop: 50,
        paddingBottom: 30,
        paddingHorizontal: 20,
    },
    closeButton: {
        position: 'absolute',
        top: 15,
        right: 15,
        zIndex: 10,
        padding: 10,
    },
    closeButtonText: {
        marginTop: 20,
        color: '#FFFFFF',
        fontSize: 24,
        fontWeight: '300',
    },
    profileSection: {
        alignItems: 'center',
        marginTop: 20,
    },
    avatarContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#E07856',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 15,
        borderWidth: 3,
        borderColor: '#FFFFFF',
    },
    avatarText: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    profileName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 5,
    },
    profileLocation: {
        fontSize: 14,
        color: '#B0B8C4',
    },
    menuSection: {
        paddingTop: 20,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 18,
        paddingHorizontal: 25,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    menuItemDanger: {
        marginTop: 10,
    },
    menuIcon: {
        fontSize: 18,
        marginRight: 15,
        width: 25,
    },
    menuText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
        letterSpacing: 0.5,
    },
    menuTextDanger: {
        color: '#FF6B6B',
    },
    editSection: {
        flex: 1,
        paddingHorizontal: 25,
        paddingTop: 20,
    },
    editTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 25,
    },
    inputLabel: {
        fontSize: 13,
        color: '#B0B8C4',
        marginBottom: 8,
        marginTop: 5,
        fontWeight: '500',
    },
    input: {
        backgroundColor: '#2e3847',
        borderWidth: 1,
        borderColor: '#4a5568',
        padding: 14,
        fontSize: 16,
        borderRadius: 10,
        marginBottom: 20,
        color: '#FFFFFF',
    },
    saveButton: {
        backgroundColor: '#4CAF50',
        padding: 16,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 10,
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontWeight: 'bold',
        fontSize: 16,
    },
    cancelButton: {
        backgroundColor: 'transparent',
        padding: 16,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#B0B8C4',
    },
    cancelButtonText: {
        color: '#B0B8C4',
        fontWeight: 'bold',
        fontSize: 16,
    },
});
export default styles;