import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    safeArea: { 
        flex: 1, 
        backgroundColor: '#F5F7FA' 
    },
    container: { 
        flex: 1 
    },
    scrollContent: { 
        flexGrow: 1, 
        paddingBottom: 30 
    },
    content: { 
        flex: 1, 
        padding: 16,
    },

    // Card de Informações Pessoais
    infoCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        shadowColor: "#4A90E2",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#2C3E50',
        marginBottom: 16,
        textAlign: 'center',
    },
    inputRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    inputWrapper: {
        flex: 1,
        marginHorizontal: 6,
    },
    inputLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#7F8C8D',
        marginBottom: 8,
        marginLeft: 4,
    },
    input: {
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        textAlign: 'center',
        color: '#2C3E50',
        borderWidth: 2,
        borderColor: '#E8EEF2',
    },
    calculateButton: {
        backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        backgroundColor: '#4A90E2',
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 12,
        shadowColor: "#4A90E2",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    calculateButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
        textAlign: 'center',
    },

    // Container da Garrafa
    bottleContainer: {
        alignItems: 'center',
        marginVertical: 20,
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 24,
        shadowColor: "#4A90E2",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    bottleWrapper: {
        alignItems: 'center',
        marginBottom: 20,
    },
    bottleCapTop: {
        width: 40,
        height: 8,
        backgroundColor: '#34495E',
        borderTopLeftRadius: 4,
        borderTopRightRadius: 4,
        marginBottom: 2,
    },
    bottleCapNeck: {
        width: 50,
        height: 20,
        backgroundColor: '#455A64',
        borderTopLeftRadius: 6,
        borderTopRightRadius: 6,
    },
    bottle: {
        width: 120,
        height: 280,
        backgroundColor: '#E8F4F8',
        borderRadius: 20,
        borderWidth: 3,
        borderColor: '#B0D4E3',
        overflow: 'hidden',
        position: 'relative',
        marginTop: 28,
    },
    waterFill: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#4A90E2',
        borderRadius: 18,
    },
    waveEffect: {
        position: 'absolute',
        top: -5,
        left: 0,
        right: 0,
        height: 10,
        backgroundColor: '#5BA3E8',
        borderRadius: 10,
    },
    bottleOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    percentageText: {
        fontSize: 36,
        fontWeight: '800',
        color: '#FFFFFF',
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },

    // Informações de Consumo
    consumptionInfo: {
        alignItems: 'center',
        width: '100%',
    },
    consumedTouchable: {
        flexDirection: 'row',
        alignItems: 'baseline',
        justifyContent: 'center',
        marginBottom: 8,
    },
    consumedText: {
        fontSize: 48,
        fontWeight: '800',
        color: '#2C3E50',
        letterSpacing: -1,
    },
    mlText: {
        fontSize: 20,
        fontWeight: '600',
        color: '#7F8C8D',
        marginLeft: 4,
    },
    editContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    editInput: {
        borderBottomWidth: 3,
        borderColor: '#4A90E2',
        fontSize: 42,
        fontWeight: '800',
        color: '#2C3E50',
        textAlign: 'center',
        minWidth: 120,
        paddingVertical: 4,
    },
    editSaveButton: {
        marginLeft: 12,
        backgroundColor: '#27AE60',
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    editCancelButton: {
        marginLeft: 8,
        backgroundColor: '#E74C3C',
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    editButtonText: {
        color: '#FFFFFF',
        fontWeight: 'bold',
        fontSize: 20,
    },
    goalText: {
        fontSize: 15,
        color: '#7F8C8D',
        marginBottom: 12,
        fontWeight: '500',
    },
    goalValue: {
        fontWeight: '700',
        color: '#4A90E2',
    },
    remainingBadge: {
        backgroundColor: '#E8F4F8',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#B0D4E3',
    },
    remainingText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#4A90E2',
    },

    // Card de Ações
    actionsCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        shadowColor: "#4A90E2",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    actionTitle: {
        fontSize: 18,
        fontWeight: '700',
        textAlign: 'center',
        color: '#2C3E50',
        marginBottom: 16,
    },
    actionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    actionButton: {
        backgroundColor: '#F8F9FA',
        padding: 16,
        borderRadius: 16,
        alignItems: 'center',
        width: '31%',
        borderWidth: 2,
        borderColor: '#E8EEF2',
    },
    actionButtonHighlight: {
        backgroundColor: '#E8F4F8',
        borderColor: '#4A90E2',
        borderWidth: 2,
    },
    actionEmoji: {
        fontSize: 32,
        marginBottom: 8,
    },
    actionButtonText: {
        color: '#2C3E50',
        fontWeight: '600',
        fontSize: 13,
        marginBottom: 4,
    },
    actionButtonValue: {
        color: '#4A90E2',
        fontWeight: '700',
        fontSize: 15,
    },
    resetButton: {
        alignSelf: 'center',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 10,
        backgroundColor: '#FFF5F5',
        borderWidth: 1,
        borderColor: '#FFCDD2',
    },
    resetButtonText: {
        color: '#E74C3C',
        fontSize: 14,
        fontWeight: '600',
    },

    // Card de Histórico
    historyCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        shadowColor: "#4A90E2",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    historyTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#2C3E50',
        marginBottom: 16,
        textAlign: 'center',
    },
    historyItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 12,
        borderRadius: 12,
        backgroundColor: '#F8F9FA',
        marginBottom: 10,
    },
    historyLeft: {
        flex: 1,
        marginRight: 12,
    },
    historyDate: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 8,
    },
    progressBarContainer: {
        height: 6,
        backgroundColor: '#E8EEF2',
        borderRadius: 3,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#4A90E2',
        borderRadius: 3,
    },
    historyRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    historyConsumed: {
        fontSize: 16,
        fontWeight: '700',
        color: '#2C3E50',
    },
    historyGoalSmall: {
        fontSize: 12,
        color: '#7F8C8D',
        marginLeft: 2,
    },
    historyCheck: {
        fontSize: 18,
        color: '#27AE60',
        marginLeft: 8,
        fontWeight: 'bold',
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 30,
    },
    emptyEmoji: {
        fontSize: 48,
        marginBottom: 12,
    },
    historyEmpty: {
        textAlign: 'center',
        color: '#95A5A6',
        fontSize: 14,
        fontWeight: '500',
    },
});

export default styles;