import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F0F4F8',
    },
    listContentContainer: {
        paddingBottom: 20,
    },
    uploadContainer: {
        paddingHorizontal: 20,
        paddingBottom: 20,
        backgroundColor: '#FFFFFF',
    },
    titulo: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#0d214f',
        marginBottom: 8,
        textAlign: 'center',
        marginTop: 20,
    },
    subtitulo: {
        fontSize: 16,
        color: '#6c757d',
        textAlign: 'center',
        marginBottom: 30,
    },
    label: {
        fontSize: 16,
        fontWeight: '600',
        color: '#343a40',
        marginBottom: 8,
        alignSelf: 'flex-start',
    },
    botaoSelecionarTipo: {
        backgroundColor: '#f8f9fa',
        borderRadius: 10,
        paddingVertical: 15,
        paddingHorizontal: 12,
        width: '100%',
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#dee2e6',
        justifyContent: 'center',
    },
    botaoSelecionarTipoTexto: {
        fontSize: 16,
        color: '#495057',
    },
    previewContainer: {
        width: '100%',
        height: 200,
        backgroundColor: '#f8f9fa',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#dee2e6',
        borderStyle: 'dashed',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        overflow: 'hidden',
    },
    placeholderContainer: {
        alignItems: 'center',
    },
    placeholderIcon: {
        fontSize: 40,
        color: '#adb5bd',
    },
    placeholderText: {
        fontSize: 16,
        color: '#adb5bd',
        marginTop: 10,
    },
    previewImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    botoesContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 20,
    },
    botaoAcao: {
        backgroundColor: '#0d214f',
        paddingVertical: 12,
        paddingHorizontal: 35,
        borderRadius: 25,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    botaoAcaoTexto: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    botaoSalvar: {
        backgroundColor: "#28a745",
        paddingVertical: 15,
        width: "100%",
        alignItems: "center",
        borderRadius: 10,
    },
    botaoSalvarDesabilitado: {
        backgroundColor: '#adb5bd',
    },
    botaoSalvarTexto: {
        color: "#FFFFFF",
        fontWeight: "bold",
        fontSize: 18,
    },
    separator: {
        borderBottomWidth: 1,
        borderBottomColor: '#dee2e6',
        marginTop: 30,
        marginBottom: 20,
    },
    separatorText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#0d214f',
        textAlign: 'center',
        backgroundColor: '#F0F4F8',
        marginTop: -12,
        alignSelf: 'center',
        paddingHorizontal: 10,
    },
    exameItemContainer: {
        flexDirection: 'row',
        padding: 15,
        marginHorizontal: 15,
        marginBottom: 15,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 5,
        elevation: 3,
        alignItems: 'center',
    },
    exameThumbnail: {
        width: 60,
        height: 60,
        borderRadius: 8,
        marginRight: 15,
        backgroundColor: '#e9ecef',
    },
    exameInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    exameTipo: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#343a40',
    },
    exameData: {
        fontSize: 14,
        color: '#6c757d',
        marginTop: 4,
    },
    exameActions: {
        marginLeft: 10,
    },
    actionTextEdit: {
        color: '#007bff',
        fontWeight: '600',
        marginBottom: 10,
    },
    actionTextDelete: {
        color: '#dc3545',
        fontWeight: '600',
    },
    listaVaziaContainer: {
        padding: 20,
        alignItems: 'center',
    },
    listaVazia: {
        fontSize: 16,
        color: '#6c757d',
        textAlign: 'center',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalView: {
        margin: 20,
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 25,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        width: '90%',
        maxHeight: '80%',
    },
    modalTitulo: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 15,
    },
    flatList: {
        width: '100%',
    },
    itemModal: {
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        width: '100%',
    },
    itemModalTexto: {
        textAlign: 'center',
        fontSize: 18,
        color: '#333'
    },
    botaoFecharModal: {
        marginTop: 15,
        backgroundColor: '#6c757d',
        borderRadius: 10,
        padding: 12,
        paddingHorizontal: 30,
        elevation: 2,
    },
    botaoFecharModalTexto: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    inputModal: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#dee2e6',
        padding: 12,
        fontSize: 16,
        borderRadius: 10,
        marginBottom: 15,
    },
    modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 10,
    },
    modalButton: {
        flex: 1,
        backgroundColor: '#007bff',
        padding: 12,
        borderRadius: 10,
        alignItems: 'center',
        marginHorizontal: 5,
    },
    modalButtonCancel: {
        backgroundColor: '#6c757d',
    },
    modalButtonText: {
        color: 'white',
        fontWeight: 'bold',
    }
});

export default styles;