import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F5F7FA',
    },
    scrollContent: {
        paddingBottom: 100,
    },
    heroContainer: {
        paddingTop: 20,
        paddingBottom: 30,
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    gaugeContainer: {
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    gaugeTextContainer: {
        position: 'absolute',
        alignItems: 'center',
        justifyContent: 'center',
    },
    gaugeValue: {
        fontSize: 48,
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: -2,
    },
    gaugeUnit: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.7)',
        fontWeight: '600',
        marginTop: -5,
    },
    gaugeStatus: {
        fontSize: 14,
        color: '#FFFFFF',
        fontWeight: 'bold',
        backgroundColor: 'rgba(0,0,0,0.2)',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 20,
        marginTop: 8,
    },
    chartContainer: {
        marginTop: 20,
        alignItems: 'center',
        paddingRight: 20, // Ajuste para o gráfico não cortar
    },
    chart: {
        borderRadius: 16,
    },
    historySection: {
        padding: 20,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2C3E50',
        marginBottom: 15,
    },
    historyItem: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 15,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
    historyIndicator: {
        width: 6,
        height: 40,
        borderRadius: 3,
        marginRight: 15,
    },
    historyContent: {
        flex: 1,
    },
    historyContext: {
        fontSize: 15,
        fontWeight: '700',
        color: '#34495E',
        marginBottom: 2,
    },
    historyDate: {
        fontSize: 12,
        color: '#95A5A6',
    },
    historyValue: {
        fontSize: 22,
        fontWeight: '900',
        marginRight: 15,
    },
    deleteBtn: {
        padding: 5,
    },
    deleteBtnText: {
        color: '#BDC3C7',
        fontSize: 16,
    },
    emptyText: {
        textAlign: 'center',
        color: '#95A5A6',
        marginTop: 20,
    },
    fab: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
    },
    fabText: {
        fontSize: 32,
        color: '#FFF',
        marginTop: -4,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 25,
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#2C3E50',
        marginBottom: 20,
    },
    input: {
        fontSize: 56,
        fontWeight: 'bold',
        color: '#2C3E50',
        textAlign: 'center',
        minWidth: 150,
        borderBottomWidth: 2,
        borderColor: '#E0E6ED',
        marginBottom: 5,
    },
    inputUnit: {
        fontSize: 18,
        color: '#95A5A6',
        marginBottom: 30,
    },
    label: {
        fontSize: 14,
        fontWeight: '700',
        color: '#7F8C8D',
        marginBottom: 10,
        alignSelf: 'flex-start',
        marginLeft: 5,
        textTransform: 'uppercase',
    },
    contextGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 30,
    },
    contextOption: {
        width: '48%',
        backgroundColor: '#F8F9FA',
        padding: 15,
        borderRadius: 12,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#F0F2F5',
    },
    contextOptionSelected: {
        backgroundColor: '#E8F4F8',
        borderColor: '#3498DB',
    },
    contextIcon: {
        fontSize: 20,
        marginRight: 10,
    },
    contextLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#7F8C8D',
    },
    contextLabelSelected: {
        color: '#2C3E50',
        fontWeight: '700',
    },
    saveButton: {
        width: '100%',
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: 'center',
        marginBottom: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    saveButtonText: {
        color: '#FFF',
        fontSize: 18,
        fontWeight: 'bold',
    },
    closeButton: {
        padding: 15,
    },
    closeButtonText: {
        color: '#95A5A6',
        fontWeight: '600',
        fontSize: 16,
    },
});

export default styles;